### ISSUE TITLE
Can't swipe under the sticky element

### ISSUE THREAD

**Issue by Hirbod** [gorhom/react-native-sticky-item#15]
When I compare to facebook, it blocks swipe when you try to swipe on the minimized element. Thats fine, the same is in your component. But when I try to swipe under the sticky item, looks like the hitslop (which is good for tapping) blocks the swipe though. Facebook allows swiping there. 

So I kinda have to swipe always using the second element. Its not super bad and not a terrible UX but it would be nice if it could accept the swipe under the minimized too.

I think the hitslop is just too big and blocks the gesture, because the right part of the first item is swipeable, but not the edge part

**Comment by Hirbod** [comment]
![IMG_0353](https://user-images.githubusercontent.com/504909/83459006-d32ed200-a463-11ea-80ea-0c728725c206.PNG)

**Comment by gorhom** [comment]
i solve this issue with #14 , but i'll cherry pick it and push it later

**Comment by gorhom** [comment]
solved with v1.3.2
