### ISSUE TITLE
react-native-sticky-item does not work with reanimated2

### ISSUE THREAD

**Issue by ayalpani** [gorhom/react-native-sticky-item#18]
Hi, thanks for this great lib!

Unfortunately, when trying to use react-native-sticky-item 2.0.0 with reanimated2, I get the following error:

"Error: Reanimated: interpolate from V1 has been renamed to interpolateNode."

**Comment by gorhom** [comment]
i will work on it later today , thanks for submitting this issue 👍

**Comment by ayalpani** [comment]
Cool, looking forward to it!

**Comment by gorhom** [comment]
this should be resolved with v2.1.0
