### ISSUE TITLE
TypeError: undefined is not a function (near '...interpolate...')

### ISSUE THREAD

**Issue by vishalpr-hs** [gorhom/react-native-sticky-item#22]
Hi,

I just update to latest React native  and I am facing this issue . 
Your help really appreciated Thanks in advance.

# Bug
TypeError: undefined is not a function (near '...interpolate...')
 

## Environment info

 "@gorhom/sticky-item": "^2.1.0",
 "react-native": "^0.64.2",
 "react-native-svg": "^12.1.0",
 "react-native-svg-animations": "^0.2.6",
  
## Exception Log

TypeError: undefined is not a function (near '...interpolate...')

This error is located at:
    in StickyItemBackground (at StickyItem.tsx:122)
    in RCTView (at View.js:34)
    in Unknown (at createAnimatedComponent.js:448)
    in AnimatedComponent(View) (at createAnimatedComponent.js:459)
    in AnimatedComponentWrapper (at StickyItem.tsx:120)
    in StickyItem (at StickyItemFlatList.tsx:249)
    in RCTView (at View.js:34)
    in Unknown (at createAnimatedComponent.js:448)
    in AnimatedComponent(View) (at createAnimatedComponent.js:459)
    in AnimatedComponentWrapper (at StickyItemFlatList.tsx:230)
    in TapGestureHandler (at StickyItemFlatList.tsx:224)
    in Unknown (at Filterslider.tsx:97)
    in RCTView (at View.js:34)
    in Unknown (at Filterslider.tsx:96)
    in RCTView (at View.js:34)
    in Unknown (at SafeAreaView.js:41)
    in SafeAreaView (at Filterslider.tsx:95)
    in Filterslider (at CategoryDetail.tsx:417)

**Comment by aleppos** [comment]
Any update?

**Comment by Hirbod** [comment]
I already submitted this on 2nd may as a ticket, now it does indeed crash with Expo SDK 42

**Comment by Hirbod** [comment]
@gorhom I isolated, that these is causing the problem:
https://github.com/gorhom/react-native-sticky-item/blob/master/src/components/sticky-item-background/StickyItemBackground.tsx#L95-L104

Unfortunately, these error messages are not helpful. I only know, removing this lines (and the assignment on `AnimatedPath` will stop the app from crashing, but the sticky item background is missing then. I am not sure, what is undefined and why it breaks).

**Comment by gorhom** [comment]
@Hirbod sorry i was busy with `BottomSheet` v4, i will look into this issue today 👍

**Comment by Hirbod** [comment]
@gorhom if you need me for testing, hit me up!

**Comment by gorhom** [comment]
this should be fix with [v2.1.1](https://github.com/gorhom/react-native-sticky-item/releases/tag/v2.1.1)

**Comment by MathewAzmat** [comment]
For **react-native-reanimated@2+** version must also add **plugins: ['react-native-reanimated/plugin']** in babel.config.js 
If you use 'interpolate' while using react-native-reanimated then please change it to 'interpolateNode'
