### ISSUE TITLE
Update an example component with Reanimated V2.

### ISSUE THREAD

**Issue by SectionTN** [gorhom/react-native-sticky-item#26]
# Feature Request

## Why it is needed

I need it in the project i'm working for, i found the idea of this component useful. 

## Possible implementation

Hey Gorhom, i love this library and i found a component same as facebook stories in library example, could you please update it to use Reanimated V2 ? i've tried but all got fail :/

### Code sample

https://github.com/gorhom/react-native-sticky-item/blob/master/example/src/components/facebook-sticky-story/FacebookStickyStory.tsx

here is the component. thanks!

**Comment by SectionTN** [comment]
@gorhom sorry for mention, any response please?

**Comment by fukemy** [comment]
hi @SectionTN , did u solved this?

**Comment by SectionTN** [comment]
> hi @SectionTN , did u solved this?

hey i'm so sorry for the late reply.
by the way, YES, i've fixed the example component, here is [it](https://github.com/MoonMeet/MoonMeet-CrossPlatform/blob/main/src/components/HomeScreen/MoonStickyStoryView.tsx)
the usage is simple no extra props.

**Comment by fukemy** [comment]
hi @SectionTN, I found you are using `interpolateNode` inside this [class](https://github.com/MoonMeet/MoonMeet-CrossPlatform/blob/main/src/components/HomeScreen/MoonStickyStoryView.tsx)

 But I found u are using `reanimated v3`, so interpolateNode deprecated, how can u run your project? Thanks
