### ISSUE TITLE
Move passed props to the end

### ISSUE THREAD

**Issue by Hirbod** [gorhom/react-native-sticky-item#5]
Hi @gorhom,

currently, you're applying the props at top
https://github.com/gorhom/react-native-sticky-item/blob/master/src/StickyItemFlatList.tsx#L176

while all of these
https://github.com/gorhom/react-native-sticky-item/blob/master/src/StickyItemFlatList.tsx#L177-L188

get appended hardcoded at the end and thus overwriting everything. While I do understand the reason behind this, since a lot of those props depend to your library, it might be worth to at least move some of them above. Specially ```decelerationRate={'fast'}``` might be something nice but imho its to slow and I would like to set it to normal.

Also the initialIndex might be something some would like to change. Could you at least consider these 2 to be set at top before ...rest so we could actually overwrite them?

**Comment by gorhom** [comment]
Hi @Hirbod , thanks for reporting this issue.

indeed `initialIndex` should not be override, i will also double check if i let `decelerationRate` to be controlled.

**Comment by Hirbod** [comment]
Hi @gorhom,

thanks, I will check that out. I see you have imported TouchableOpacity from RNGH, let me see if this works for me without that (cause I am using TouchableScale).
And I've seen that you implemented getItemLayout (I also did this locally, but even better if the library takes care of that)

I'll report back, gonna test this now

**Comment by gorhom** [comment]
this been fixed with [Release v1.2.0](https://github.com/gorhom/react-native-sticky-item/releases/tag/v1.2.0)

**Comment by Hirbod** [comment]
What about decelerationRate?

**Comment by gorhom** [comment]
@Hirbod it will be shipped in the next release 👍
