### ISSUE TITLE
Feat: Feedback on StickyItemPress

### ISSUE THREAD

**Issue by Hirbod** [gorhom/react-native-sticky-item#7]
Hi @gorhom,

since we've come so far, I have a last feature request: there is no Feedback on Sticky-Item Press (neither when shrinked nor when its first index).

Maybe also a TouchableOpacity with a passable activeOpacity? What do you think?

**Comment by gorhom** [comment]
released with [v1.3.0](https://github.com/gorhom/react-native-sticky-item/releases/tag/v1.3.0)
